# https://www.youtube.com/watch?v=f-7HP9doQOQ   CodeWriter
# 
version: '3'

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
# посмотреть варианты рестарта (unless-stopped - не перегружать без ведома)
    restart: always
    depends_on:
        - php
        - mysqldb

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

    phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - 9090:80
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306
      depends_on:
            - mysqldb
      